#!/usr/bin/env python3
"""Build the contents list for /gologorica-line/.

The page carries 76 numbered sections and had no way into them: a reader who
arrived at a finding's anchor could not see what else the page held, and a
reader who arrived at the top had 900 KB of prose and no index. The headings
already exist in gologorica.json; what was missing was their ORDER, which
lives only in the markup. So read the markup.

Emits site/src/data/gologorica-toc.json as [{id, heading}] in page order.
check-golo-toc.py fails the gate if this file and the page disagree.
"""
import json, re, sys, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
ast = (ROOT/"site/src/pages/gologorica-line.astro").read_text()
g = json.loads((ROOT/"site/src/data/gologorica.json").read_text())

pairs = re.findall(r'<h2 id="([A-Za-z0-9_-]+)">\{g\.([A-Za-z0-9_]+)\.heading\}</h2>', ast)
out = []
for anchor, key in pairs:
    h = g.get(key, {}).get("heading")
    if not h:
        print("build-golo-toc: FAIL — no heading for g.%s" % key); sys.exit(2)
    out.append({"id": anchor, "heading": h})

# every <h2 id="..."> on the page must be accounted for, or the contents lie
all_ids = re.findall(r'<h2 id="([A-Za-z0-9_-]+)"', ast)
missing = [i for i in all_ids if i not in {o["id"] for o in out}]
if missing:
    print("build-golo-toc: FAIL — %d section(s) the contents cannot name: %s"
          % (len(missing), ", ".join(missing))); sys.exit(2)

(ROOT/"site/src/data/gologorica-toc.json").write_text(
    json.dumps({"note": "Generated by scripts/build-golo-toc.py. Page order, not file order.",
                "rows": out}, ensure_ascii=False, indent=1))
print("build-golo-toc: %d sections" % len(out))
