#!/usr/bin/env python3
"""Build web plates from the family's own scans and photographs.

Reads from the owner's document folder, writes optimised WebP into
site/public/plates/ plus a manifest at site/src/data/plates.json.

Nothing is invented here: every plate carries the archive or holder it
came from, and the caption says only what the image itself shows.
"""
import json, os, subprocess, sys

DOCS = os.path.expanduser("~/Documents/Genealogy & Family History/Defranceski")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, "site", "public", "plates")
MAN  = os.path.join(ROOT, "site", "src", "data", "plates.json")

# id, source file (relative to DOCS), rotate, group, title, caption, holder
PLATES = [
 # ---- photographs, Omiš branch -------------------------------------------
 ("omis-josip-anna-ante", "Omis Branch/Omis Defranceski's/Josip and Anna with Baby Ante.jpg", 0,
  "photographs", "Josip and Anna, with Ante",
  "A studio portrait: Josip seated in a light suit and loose cravat, Anna in a dark bodice with the high collar and gathered shoulders of the 1890s, the baby Ante across her lap in a striped romper. The painted backdrop and the vignetted edge are the marks of a small provincial photographer.",
  "Family collection (Omiš branch)"),
 ("omis-zane", "Omis Branch/Omis Defranceski's/zane defranceschi.jpg", 0,
  "photographs", "Zane Defranceschi",
  "A man in a white peaked cap, shirtsleeves and wide trousers, seated on a rush-bottomed chair against a whitewashed wall, a barefoot boy leaning on his shoulder. Zane is the Venetian form of Giovanni — the same name the parish clerks wrote as Zuane.",
  "Family collection (Omiš branch)"),
 ("omis-zane-group", "Omis Branch/Omis Defranceski's/zane defranceschi middle front.jpg", 0,
  "photographs", "Zane, middle front",
  "A group photograph kept with the Omiš papers; the family's note places Zane in the middle of the front row.",
  "Family collection (Omiš branch)"),
 ("omis-anton-1932", "Omis Branch/Omis Defranceski's/Anton Toni Franceschi 1932.jpg", 0,
  "photographs", "Anton “Toni” Franceschi, 1932",
  "Dated by the family to 1932. Note the surname as written on the print: Franceschi, without the particle — the Omiš branch dropped and resumed it by turns.",
  "Family collection (Omiš branch)"),
 ("omis-frane", "Omis Branch/Omis Defranceski's/Frane Defranceski.jpg", 0,
  "photographs", "Frane Defranceski",
  "Frane is the Croatian form of Francesco; the surname on this print is spelled the Croatian way, Defranceski.",
  "Family collection (Omiš branch)"),
 ("carlo-portrait", "Seget & Istra Branch/Seget - Villa Defranceski in Istra/Carlo De Franceschi.jpg", 0,
  "photographs", "Carlo De Franceschi in old age",
  "The historian of Istria, born at Gologorica in 1809, photographed late in life: round spectacles, white beard, dark stock. He died in 1893.",
  "Reproduced in the Seget monograph"),

 # ---- displaced-persons portraits, Crikvenica family ---------------------
 ("fiche-petar", "Peter Defranceski/peter/a.jpg", 0,
  "dp", "Petar Defranceski — Fiche Individuelle",
  "The French-zone camp card. Petar, born 15 June 1913 at Crikvenica, Yugoslav, profession auto-mécanicien, employer's address Kelterstr. 30 Neuhausen, married. Five fingerprints in red, a passport photograph clipped at the top right, file 148.902 / 30609.",
  "International Tracing Service / Arolsen Archives"),
 ("fiche-zdravko", "Peter Defranceski/peter/400.jpg", 0,
  "dp", "Zdrafko Defranceski — Fiche Individuelle",
  "Born 1 April 1921, Yugoslav, auto-mécanicien, married. File 148.901 / 30560. The same trade as Petar, and the same camp office.",
  "International Tracing Service / Arolsen Archives"),
 ("fiche-ruza", "Peter Defranceski/peter/800.jpg", 0,
  "dp", "Ruža Defranceski — Fiche Individuelle",
  "Born 1922, no profession recorded, married. In the photograph she wears a cross at her throat and holds her infant son, who is not named here: he was born in 1944 and may be living.",
  "International Tracing Service / Arolsen Archives"),

 # ---- the wartime and displaced-persons paper ---------------------------
 ("its-pfullingen-list", "Peter Defranceski/peter/000.jpg", 0,
  "documents", "Foreigners registered at Pfullingen, 1939–45",
  "“Aufstellung über die in der Zeit vom 1. Sept. 1939 – 25. April 1945 in der Vorstadt Pfullingen gemeldet gewesenen Ausländer. Hier: Kroatien.” Drawn up at Reutlingen-Pfullingen on 10 March 1947. Six Defranceskis are listed, five of them born at Crikvenica.",
  "International Tracing Service / Arolsen Archives"),
 ("its-cover", "Peter Defranceski/peter/1050.jpg", 0,
  "documents", "ITS file cover D-1.505",
  "The tracing-service wrapper for the family: Petar, his wife Luise née Salzer of Neuhausen, and two daughters born at Urach and Metzingen during the war.",
  "International Tracing Service / Arolsen Archives"),
 ("cm1-identity", "Peter Defranceski/peter/1051.jpg", 0,
  "documents", "CM/1 application, identity page",
  "The IRO care-and-maintenance application, 7 November 1947. Petar gives his nationality at birth as Austria-Hungary, his address as Kelternstr. 30 Neuhausen, and the country he wants to be resettled in as the United States — California.",
  "International Tracing Service / Arolsen Archives"),
 ("cm1-detail", "Peter Defranceski/peter/1052.jpg", 0,
  "documents", "CM/1 application, history page",
  "Residences, trades and schooling: Split 1937–39 with Jugoslav Lloyd as a ship's engineer, then Germany from April 1939; car-mechanic examination at Reutlingen in 1947; a truck valued at 15,000 among his assets; and an aunt, Jacomina Alafetić, at San Pedro, California.",
  "International Tracing Service / Arolsen Archives"),
 ("kk-felix", "Peter Defranceski/peter/1000.jpg", 0,
  "documents", "Felix Defranceski — sickness-fund card",
  "Felix, born 1908 at Crikvenica, single, living at Pfullingerlandstraße in Reutlingen. Employers from July 1941: Hermann Sauer of Pfullingen as a motor mechanic, then Wilhelm Heim as a driver, then Sauer again.",
  "International Tracing Service / Arolsen Archives"),
 ("kk-ivan", "Peter Defranceski/peter/1002.jpg", 0,
  "documents", "Ivan Defranceski — sickness-fund card",
  "Ivan, born June 1925 at Crikvenica, single, Brunnenstraße 7, Pfullingen. He entered work on 21 October 1941, aged sixteen, as a Hilfsarbeiter — an unskilled hand.",
  "International Tracing Service / Arolsen Archives"),
 ("kk-petar", "Peter Defranceski/peter/1003.jpg", 0,
  "documents", "Petar Defranceski — sickness-fund card",
  "Marked “Kroate” in the top margin. Employed by Hermann Sauer of Reutlingen on motor-vehicle repairs from 1 April 1942 to 2 March 1945 — the card runs out three weeks before the French army reached the town.",
  "International Tracing Service / Arolsen Archives"),
 ("kk-zdravko", "Peter Defranceski/peter/1005.jpg", 0,
  "documents", "Zdravko Defranceski — sickness-fund card",
  "Below the employment lines, a clerk has pencilled a short life: in Croatia 1936–43; taken by the Partisans in 1943; three or four months in captivity; then straight to Germany.",
  "International Tracing Service / Arolsen Archives"),
 ("cert-anton-1890", "Peter Defranceski/peter/1006.jpg", 0,
  "documents", "Anton Defranceski, born 1890 — municipal certificate",
  "Certified by the mayor of Pfullingen, Kreis Reutlingen, on 28 February 1950: Anton Defranceski, born 20 January 1890 at Crikvenica, Croatia-Yugoslavia, lodged at Pfullingen, workplace Hermann Sauer, Reutlingen-Süd.",
  "International Tracing Service / Arolsen Archives"),
 ("roll-1949", "Peter Defranceski/peter/1100.jpg", 0,
  "documents", "Resettlement roll, February 1949",
  "Lines 58–60 of a nominal roll dated 22 February 1949: Zdrafko, Ruža and their son, Yugoslavs from Crikvenica and Fužine, at Reutlingen, with IRO numbers against each name.",
  "International Tracing Service / Arolsen Archives"),

 # ---- Gračišće: the parish record of the direct line -----------------
 ("dapa-letter-1", "Unsorted Scan - [Unread] Epson_27072021203248.jpg", 0,
  "gracisce", "Državni arhiv u Pazinu to David Defranceski, 26 April 2021",
  "The Pazin State Archive answers a request made eight days earlier: the copy from the Gračišće birth register for Josip Defranceschi is enclosed. Itemised at 117 kuna — research 50, certified A3 copy 7, overseas postage 60.",
  "Državni arhiv u Pazinu (DAPA)"),
 ("gracisce-1863", "Unsorted Scan - [Unread] Epson_27072021203422.jpg", 0,
  "gracisce", "Liber Baptizatorum, Gračišće 1841–1899",
  "Certified and stamped by the Pazin State Archive. The register is ruled for house number, the child's name and date of birth, religion, sex, legitimacy, both parents with the father's condition, the godparents and the midwife. The entry taken out for this family is Josephus, born 22 March 1863, son of Antonius Defranceschi, lapicida — a stonecutter.",
  "Državni arhiv u Pazinu (DAPA), MKR Gračišće 1841–1899"),
 ("dapa-letter-2", "Unsorted Scan - [Unread] Epson_27072021203523.jpg", 0,
  "gracisce", "Državni arhiv u Pazinu, 24 June 2021",
  "A second answer, this time for Antonius Defranceschi and his family, and for Giovanni Battista Defranceschi and his family — the two Status Animarum entries opposite. 124 kuna.",
  "Državni arhiv u Pazinu (DAPA)"),
 ("status-animarum-gb", "Unsorted Scan - [Unread] Epson_27072021203744.jpg", 90,
  "gracisce", "Status Animarum — house 5, Gallignana",
  "The book of souls for the parish of Gallignana. House 5: Joan. Bapt. Defranceschi, agricola, born 13 August 1787, married 1819, died 1 September 1846; his wife Francisca Salomon, born 17 March 1797; and their sons Raymundus, Antonius, Joannes and Franciscus.",
  "Državni arhiv u Pazinu (DAPA), ZM34K 217, M01072071"),
 ("status-animarum-ant", "Unsorted Scan - [Unread] Epson_27072021203849.jpg", 90,
  "gracisce", "Status Animarum — house 19, Gallignana",
  "House 19: † Antonius Defranceschi q. Joannis — son of the late Giovanni — born 20 September 1825, married 25 November 1856, died 4 August 1894; his wife Maria née Fernasar, born 17 October 1832; and their children Antonius, Josephus, Leopolda, Catharina and Modestus.",
  "Državni arhiv u Pazinu (DAPA), ZM34K 217, M01071656"),

 # ---- the Vinodol and Pazin registers ------------------------------------
 ("ana-kalanj", "Birth, Death & Marriage Records/Ana Kalanj Defranceski Birth.jpg", 0,
  "gracisce", "Anna Kalanj, born 3 January 1864",
  "Entry 2 for 1864 in the baptismal register of Ledenice, the Vinodol parish above Crikvenica. Anna, legitimate, daughter of Josephus Kalanj and Rosalia née Perković, at Rijenovica house 22; godparents Josephus Ban and his wife Anna; baptised by Vincentius Segulja, parish priest. The other entries on the page are Perković, Butković, Mataija, Semper — the surnames of one valley.",
  "Državni arhiv / matične knjige, Ledenice"),
 ("carlo-witness", "Birth, Death & Marriage Records/antonio Covaz : Covach Marriage.jpg", 0,
  "documents", "Carlo De Franceschi signs as a witness, Pazin 1842",
  "The Pisino marriage register, 13 September 1842. Antonius Covach, 22, of house 33, marries Hedwiges Mrak, 17, of house 30. In the column for witnesses: «Carolus Defranceschi» and «Aegidius Mrach», and against their names their conditions — «I. R. Auscultans» and «studiosus». Imperial-Royal Auscultator was the entry rank of the Austrian judicial service. Carlo was thirty-two.",
  "Hrvatski državni arhiv, HDA 583"),
 ("anton-1890", "Birth, Death & Marriage Records/Anton rudolph birth.png", 0,
  "gracisce", "Anton Rudolf, born 20 January 1890",
  "Entry 9 in the Croatian-language baptismal register: Anton Rudolf, born 20 January 1890, baptised 9 February, legitimate, son of «Josip Defranceschi i žena Ana Kalanj rodjena». Residence: Klenovica house 22 — and beside it, in the column for the parents' place of origin, «Gallignana u Istriji». Godfather Jakov Kalanj of the same house 22; baptised by Matej Butković, parish priest.",
  "Matične knjige, Ledenice / Klenovica"),
 ("nodburga-1794", "Birth, Death & Marriage Records/Nodburgam defranceschi.png", 0,
  "documents", "Nodburga Defranceschi marries at Bakar, 1794",
  "27 February 1794, dispensed from the third banns by the Bishop: in the church of the Blessed Virgin Mary, the marriage of Dominus Joannes Vorkret and Domicella Nodburga Defranceschi, blessed by Canon Antonius de Agnesis, in the presence of the Vice-Governor Aloysius de Orlando and the noble Antonio Maria ab Orebich, assessor of the community of Buccari. Notburga is a Tyrolean saint's name, and an odd one to find on the Kvarner coast.",
  "Matične knjige, Bakar (Buccari)"),
 ("cm1-zara", "Birth, Death & Marriage Records/001.jpg", 0,
  "dp", "Antonio Defranceschi of Zara — refused",
  "A second IRO application, completed at Bolzano on 10 May 1950. Antonio Defranceschi, born 18 January 1905 at Zara, ethnic group Italian, son of Riccardo and Giuseppina Zersuscek; his wife Antonietta née Stipanovich, born 1910, daughter of Sabino Stipanovich and Maria Lovrich. Clerk at Zara to 1941, then a soldier in the Italian army until the capitulation, then Zara again until January 1944, then Italy. Twice across the form, in blue crayon: NOT WITHIN THE MANDATE OF IRO.",
  "International Tracing Service / Arolsen Archives"),
 ("edoardo-1899", "Birth, Death & Marriage Records/Edoardo De Franceschi Birth.png", 0,
  "documents", "Edoardo De Franceschi dies at San Daniele del Friuli, 1899",
  "Atti di morte no. 28, San Daniele del Friuli, 12 August 1899: at five in the morning there died in the Civic Hospital «De Franceschi Edoardo, di anni quarantotto, già Ufficiale, nato in Zara e domiciliato in Zara, figlio del fu Giovanni e della fu Zenardi Maria, coniugato a Pappafava Regina» — a former officer of Zadar, forty-eight, seven hundred kilometres from home.",
  "Comune di San Daniele del Friuli, Atti di morte"),
 ("pietro-1895", "Birth, Death & Marriage Records/Pietro de Franceschi Death.png", 0,
  "documents", "Pietro De Franceschi dies at San Daniele del Friuli, 1895",
  "Atti di morte no. 19, 30 March 1895, in the same hospital four years earlier: «De Franceschi Pietro, di anni quarantaquattro, mura…» — a mason, forty-four. The trade of the Gračišće line, in the country the family says it came from.",
  "Comune di San Daniele del Friuli, Atti di morte"),
 # ---- the Crikvenica house: the family's own photographs ------------------
 ("josip-bepo", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/3B4FE855-3841-448A-81E1-56B5B8B69836-3200-00004.jpg", 0,
  "photographs", "Josip “Bepo” de Franceschi",
  "A hand-tinted studio portrait, one of a matched pair with the woman opposite — almost certainly a marriage pair. Dark hair swept back, a full beard, a bow tie. The family file dates him 1870; the Gračišće register makes the man of this name and place born 22 March 1863.",
  "Family collection (Crikvenica)"),
 ("ana-portrait", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/C4429E20-A431-46E6-AD10-9EF6FEEFC3AD-3200-00004.jpg", 0,
  "photographs", "Ana, the companion portrait",
  "The other half of the pair: a young woman in a high-necked dress with lace at the cuffs, hair dressed up, hand resting on a chair back. Tinted the same warm brown by the same hand.",
  "Family collection (Crikvenica)"),
 ("ana-grave", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/E3C4209D-62A5-4FB5-B8C8-0FE78294B34C-1084-00000.jpg", 0,
  "graves", "The grave of Ana de Franceschi",
  "A standing stone with a cross and two oval porcelain medallions — a woman, and a man in a fedora. «Ovdje počiva u miru Božjem — ANA DE. FRANCESCHI — ✱ 19.IX.1863 ✝ 28.V.1936». Here rests in God's peace. Below the dates the word «suprug», husband, begins a second inscription that the photograph cuts off.",
  "Family collection (Crikvenica)"),
 ("ursula-kovacina", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/240B6E96-4B3A-4519-A644-C1170908A26F-1084-00000.jpg", 0,
  "photographs", "Ursula, born Kovačina",
  "Anton Rudolf's wife, and the mother of the four brothers who ended up in Württemberg. Seated, in the loose drop-waisted dress of the early 1920s, something folded in her lap. The print is worn to the emulsion at every corner.",
  "Family collection (Crikvenica)"),
 ("ursula-old", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/1F109C65-C478-45C8-A664-77BA7A05B05E-1084-00000.jpg", 0,
  "photographs", "Ursula in old age, with a grandchild",
  "Colour, 1960s or 70s. She sits among stacked café chairs on a seafront, a small child standing against her knee, a traffic policeman in white passing behind. The child is not named here.",
  "Family collection (Crikvenica)"),
 ("petar-portrait", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/3E5AEA06-ADDE-4007-BD24-017793E3345C-1084-00000.jpg", 0,
  "photographs", "Petar Defranceski",
  "A studio portrait in a double-breasted pinstripe. Set this beside the photograph clipped to his French camp card in 1947 and it is plainly the same man: the same long jaw, the same swept hair.",
  "Family collection (Crikvenica)"),
 ("petar-pilot", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/80C31A8F-5F06-443E-A856-1D0919BD1CFA-1084-00000.jpg", 0,
  "photographs", "“Peter (Senior), pilot in war”",
  "A young man in a leather flying helmet with the goggles pushed up on his forehead, and a sheepskin-collared flying jacket. The family's own caption calls him Peter Senior, a pilot in the war. Nothing in the displaced-persons file mentions flying: there he is a ship's engineer with Jugoslav Lloyd, and then a motor mechanic.",
  "Family collection (Crikvenica)"),
 ("zdravko-portrait", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/678C8719-CC46-46A0-B90F-351ECCA488D5-1084-00000.jpg", 0,
  "photographs", "Zdravko Defranceski",
  "A studio portrait in a wide-lapelled pinstripe suit, hair oiled back — the same face as the French camp card of 1947, a few years and a good deal of trouble apart.",
  "Family collection (Crikvenica)"),
 ("zdravko-plaque", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/633E7C58-C84F-4AEE-8C0B-78FAD7BF1AB8-1084-00000.jpg", 0,
  "graves", "Zdravko's plaque at Horsham",
  "«In loving remembrance of ZDRAVKO FRANK DEFRANCESKI, died 22nd December 1979 aged 58, beloved husband of Rosa, loved father of Anton and Vivian, loved grandfather of Dean, Lisa, Antonia and Carla. Resting in God's loving care.» A bronze plaque in a lawn cemetery in the Victorian Wimmera, for a man born at Crikvenica.",
  "Family collection"),
 ("ruza-portrait", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/1C984653-95A6-463E-A4DC-78BE109E7B3F-1084-00000.jpg", 0,
  "photographs", "Ruža, born Hreljac",
  "A young woman with a flower pinned in her hair, photographed in the 1940s. Born at Fužine on 13 February 1922; died 30 January 1996 and buried at Horsham beside Zdravko.",
  "Family collection"),
 ("ivan-grave", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/DB666218-D3CD-41E0-BDD3-CFEAB940975C-1084-00000.jpg", 0,
  "graves", "The grave of Ivan Defrančeski, 1925–1995",
  "Polished dark granite, a plain incised cross, and the name cut in Croatian orthography: IVAN DEFRANČESKI, 1925–1995. Flowers and photographs on the neighbouring slabs. The boy who entered a Reutlingen factory at sixteen in October 1941 went home, and is buried on his own coast.",
  "Family collection"),
 ("anton-child", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/AEC71C94-55A9-425C-8054-FCD16E91271C-1084-00000.jpg", 0,
  "photographs", "Anton, as a boy",
  "The child written on the French camp card in 1947 with the single word «enfant» across the fingerprint boxes, and photographed that year in his mother's arms. Here he is a few years older, in a dark pinafore over a knitted jumper. The print is torn across one corner. He died at Ipswich, Queensland, in 1999.",
  "Family collection"),
 ("pepe-sailors", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/1F654D70-86AE-4B55-966A-294D98AE2D9D-1084-00000.jpg", 0,
  "photographs", "Pepe, centre, with four sailors",
  "Five young men in naval ratings' uniform and round caps, shoulder to shoulder against a hedge. The family caption puts Pepe in the middle. Interwar, and the Adriatic: these are Yugoslav navy caps.",
  "Family collection (Crikvenica)"),
 ("pepe-pier", "Family Tree Files/Defranceski Family Tree1.mftpkg/resources/pictures/E85DAF89-1029-43B0-A2C9-AF1459445543-1084-00000.jpg", 0,
  "photographs", "Pepe on the sea wall",
  "A man in shirtsleeves sitting on a harbour parapet, a bay and a low waterfront behind him, boats out on the water. The photographer's blindstamp in the corner reads ZORA.",
  "Family collection (Crikvenica)"),

 # ---- the villa at Seget --------------------------------------------------
 ("villa-facade", "Seget & Istra Branch/Seget - Villa Defranceski in Istra/Picture 1.jpg", 0,
  "places", "Stancija Seghetto — the manor house",
  "The front Giorgio de Franceschi (1788–1865) commissioned in 1843–45: two giant pilasters flanking the centre, two orders of six windows, a great round-arched portal, and a tympanum over all. Neoclassical, in the manner of the second quarter of the nineteenth century, grafted onto a Venetian country house of the seventeenth.",
  "Family collection (Seget)"),
 ("villa-tympanum", "Seget & Istra Branch/Seget - Villa Defranceski in Istra/Picture 3.jpg", 0,
  "places", "The arms in the tympanum",
  "A circular medallion set in the pediment, with a shield carved in relief inside it, and below, lozenge panels with rosettes. La Voce del popolo records the arms here as «troncato di azzurro e d'oro al leone rampante al naturale». At this resolution the carving cannot be read as heraldry — the shape of a shield is legible and nothing inside it is. A proper photograph would settle it.",
  "Family collection (Seget)"),
 ("villa-tower", "Seget & Istra Branch/Seget - Villa Defranceski in Istra/Picture 8.jpg", 0,
  "places", "The crenellated tower",
  "«La torre con merlature, ubicata a nord-ovest rispetto alla casa dominicale» — the battlemented tower north-west of the manor, built to watch the property, and badly restored at the end of the twentieth century. It stands at the roadside with a vine over its shoulder.",
  "Family collection (Seget)"),
 ("villa-rustici", "Seget & Istra Branch/Seget - Villa Defranceski in Istra/Picture 4.jpg", 0,
  "places", "The rustic range behind the house",
  "Arcaded outbuildings in bad repair: the coach house, the produce stores and the colonists' dwellings. The nineteenth-century oil mill stood among these, with its presses and a dozen stone oil jars, until it was converted into a house about twenty years ago.",
  "Family collection (Seget)"),
 ("villa-well", "Seget & Istra Branch/Seget - Villa Defranceski in Istra/Picture 6.jpg", 0,
  "places", "The well",
  "A stone wellhead with an iron arch over it, in what is now a garden. The whole holding was walled, and this stood inside it.",
  "Family collection (Seget)"),
 # ---- Mione: the civil registers of the Carnian homeland ------------------
 ("mione-index", "Antenati - Mione/Mione-Nati-indice-1806-1810.jpg", 0,
  "gracisce", "The Mione birth index, 1806–1810",
  "«Dipartimento di Passariano, Distretto di Tolmezzo, Cantone di Rigolato, Comune di Mione — Tavola alfabetica per gli Atti di Nascita ch'ebbero luogo dall'anno 1806 all'anno 1810.» The first three lines of the alphabet are Defranceschi Anna-Maria, Defranceschi Anna-Cecilia and De Franceschi Gio: Batta. Four Erman entries follow a few lines down — the other family named in the headmen's list of 1679.",
  "Archivio di Stato di Udine, Stato civile napoleonico, Mione, sig. 12954"),
 ("mione-1809-32", "Antenati - Mione/Mione-Nati-1809-atto-32-AnnaMaria.jpg", 0,
  "gracisce", "Anna Maria de Franceschi, Muina, 30 December 1809",
  "Act 32, the last of the year. The midwife Speranza, wife of Antonio Salante, aged fifty-nine, of Muina, presented a girl born that morning at eleven, named Anna Maria — daughter of «Osvaldo de Franceschi e di Appolonia Salante sua consorte, ambedue agricoltori domiciliati in esso villaggio». Registrar: Giacomo Micoli.",
  "Archivio di Stato di Udine, Stato civile napoleonico, Mione, Nati 1809"),
 ("mione-1810-1", "Antenati - Mione/Mione-Nati-1810-atto-1-AnnaCecilia.jpg", 0,
  "gracisce", "Anna Cecilia de' Franceschi, Mione, 14 January 1810",
  "Act 1 of 1810. «Francesco de' Franceschi d'anni ventisei circa, di professione Sarto» — a tailor, aged about twenty-six — brought his daughter, born that morning at three, and named her Anna Cecilia; her mother is «Margherita nata Gortan sua consorte». He signs the register himself. Act 2 below names Pasqua de' Franceschi, wife of Pietro Luchin of Mione.",
  "Archivio di Stato di Udine, Stato civile napoleonico, Mione, Nati 1810"),
 ("mione-1810-21", "Antenati - Mione/Mione-Nati-1810-atto-21-GioBatta.jpg", 0,
  "gracisce", "Giovanni Battista De Franceschi, Mione, 15 October 1810",
  "Act 21. «De Franceschi Osualdo d'anni ventisei, di professione fa legname» — a carpenter — presented his son, born at ten that morning in the contrada of Mione, and named him Gio: Batta. The mother is «Cattarina nata Brencis sua consorte». Witnesses: a shoemaker and a tailor, both of Luint. He signs.",
  "Archivio di Stato di Udine, Stato civile napoleonico, Mione, Nati 1810"),
 ("mione-matr-index", "Antenati - Mione/Mione-Matrimoni-indice-1806-1810.jpg", 0,
  "gracisce", "The Mione marriage index, 1806–1810",
  "Two De Franceschi marriages in one small book. The first line of the alphabet: «Salante Appolonia con Defranceschi Osualdo — di Muina — 28 Gennajo 1808». Further down: «Prencis Valentina con Defranceschi Osualdo — di Mione — 6 Agosto 1807».",
  "Archivio di Stato di Udine, Stato civile napoleonico, Mione, sig. 12987"),
 ("mione-matr-1808", "Antenati - Mione/Mione-Matrimoni-1808-atto-1-Osvaldo-Appolonia.jpg", 0,
  "gracisce", "Osvaldo de Franceschi marries Appolonia Salante, 28 January 1808",
  "The deepest document in this archive. Osvaldo de Franceschi, farmer, aged twenty, of Muina, «figlio di Antonio de Franceschi, e di Maria nata Corva, pure agricoltori», marries Appolonia Salante, aged twenty-five and a half, daughter of Antonio Salante and Speranza née Micoli. His birth act is read out: born 14 March 1788 at Muina, «da legittimo Matrimonio di Antonio qm. Leonardo de Franceschi, e di Maria nata Corva» — Antonio, son of the late Leonardo. His father's written consent is dated 25 October 1807. Four witnesses, three of them Micoli of Muina. Both spouses sign.",
  "Archivio di Stato di Udine, Stato civile napoleonico, Mione, Matrimoni 1808, atto 1"),
 ("mione-matr-1806", "Antenati - Mione/Mione-Matrimoni-1806-Giacoma-deFranceschi.jpg", 0,
  "gracisce", "Giacoma de Franceschi marries, 7 August 1806",
  "The earliest De Franceschi act found in Carnia. At Mione, in the «Distretto della Carnia, Cantone di Gorto», Giacoma de Franceschi — seventeen years, two months and twelve days old, «figlia del fu Osualdo de Franceschi, e di Catterina nata Fabris» — marries Ignazio di Prato, a merchant of Chialina. Her birth act of 25 May 1789 is read into the record. She signs herself «Giacoma de Franceschi q.m Osualdo». All four witnesses are tailors; the registrar is Giovanni Micoli-Toscano and the secretary Battà Micoli-Toscano.",
  "Archivio di Stato di Udine, Stato civile napoleonico, Mione, Matrimoni 1806"),
 ("mione-morti-index", "Antenati - Mione/Mione-Morti-indice-1806-1810.jpg", 0,
  "gracisce", "The Mione death index, 1806–1810",
  "Eight Defranceschi entries: Maria 1807, Lucia and Francesco Antonio 1808, Leonarda 1808, Anna Cecilia in January 1810 eleven days after her birth, Sebastiano «chierico» in July 1810, Maddalena in August and Mariana in September. Corva and Erman entries stand among them.",
  "Archivio di Stato di Udine, Stato civile napoleonico, Mione, sig. 12966"),
 ("mione-fede-1789", "Antenati - Mione/Mione-1806-fede-battesimale-Giacoma-1789.jpg", 0,
  "gracisce", "The parish certificate of 1806, reaching back to 1789",
  "Filed with the marriage as an allegato, under a two-and-sixpence revenue stamp of the Kingdom of Italy: «Certifico io sottoscritto Parroco della Pieve Matrice di Gorto a parte Luvincis, come Giacoma figlia legitima e naturale di OSUALDO QUONDAM GIO: BATTA DE' FRANCESCHI DI MIONE, e di Cattarina sua moglie, essa è nata li 25 del mese di Maggio nell'anno 1789, come consta dal Libro dei Battezzi.» Signed and sealed by D. Gio: Batta Dario, pievano, at Luincis on 5 August 1806, and countersigned at Mione by the mayor Giovanni Micoli-Toscano.",
  "Archivio di Stato di Udine, Stato civile napoleonico, Mione, Matrimoni allegati 1806"),
 ("mione-consenso-1805", "Antenati - Mione/Mione-1806-consenso-notarile-Chialina.jpg", 0,
  "gracisce", "A notary's extract from Chialina, 8 October 1805",
  "Catterina, widow of the late Gio: Giacomo di Prato of Chialina, could not attend the signing of the marriage contract between her son Ignazio and «Giacoma figlia di D.no Osualdo de' Franceschi di Mione», so she appeared before the notary and declared her assent. Drawn by Antonio di Prato, notary. Note the style given to Giacoma's father: Dominus.",
  "Archivio di Stato di Udine, Stato civile napoleonico, Mione, Matrimoni allegati 1806"),
 # ---- Arolsen, found 2026 -------------------------------------------------
 ("reutlingen-list", "Arolsen - new 2026/Reutlingen-list-Yugoslav-nationals-Felix-1941-42.jpg", 0,
  "documents", "Yugoslav nationals resident at Reutlingen",
  "Not the Pfullingen list, but the town's own: «Liste der im Stadtgebiet Reutlingen mit Betzingen und Sondelfingen wohnhaft gewesenen jugoslavischen Staatsangehörigen». Line 16 is Defranceski Felix, born 14.1.08 at Crikvenica, present from 15 August 1941 to 8 October 1942. Read the lines around him: Brozicevic, Car, three Domijans and Dracic, every one of them born at Crikvenica, arriving from October 1938.",
  "Arolsen Archives, DE ITS 2.1.3.1 BW 029 7 JUG ZM"),
 ("petar-counselling", "Arolsen - new 2026/Petar-counselling-fiche-1949-1951-stays-in-Germany.jpg", 0,
  "dp", "Petar decides to stay — the counselling card, 1949–51",
  "A resettlement counselling card for Peter and Luise Defranceski, IRO 148.902, at Kelternstraße 30, Neuhausen. Three lines under EXPOSÉ settle what became of the plan to go to California. 22 July 1949: «Veut rester en Allemagne, a une maison, 2 autos etc.» — wants to stay in Germany, has a house, two cars. 28 April 1951: confirms the family wish to remain. 25 May 1951: listed among displaced persons living privately.",
  "Arolsen Archives, ITS 3.1.1.1, folder DP0758"),
 ("petar-fiche-colour", "Arolsen - new 2026/Petar-fiche-individuelle-original-colour.jpg", 0,
  "dp", "Petar's camp card — the original",
  "The same Fiche Individuelle the family holds as a faint photocopy, here in the original: the clipped passport photograph legible, the five fingerprints in red, «Auto-mecancien», Kelterstr. 30 Neuhausen, file 148.902 CB and 30609.",
  "Arolsen Archives, ITS 3.1.1.1, folder DP0758"),
 ("felix-card-colour", "Arolsen - new 2026/Felix-Krankenkasse-card-colour-original.jpg", 0,
  "documents", "Felix's sickness-fund card — the green original",
  "The Allgemeine Ortskrankenkasse membership and benefit card in its original green, stamped DOCUMENT EXPLOITÉ. Felix Defranceski, born 14.1.08 at Ericvenica, single, of Reutlingen, Pfullingerlandstraße. Four employments between July 1941 and October 1942, three of them for Hermann Sauer.",
  "Arolsen Archives, ITS 2.2.2.1 War Time Card File"),
 ("pfullingen-legible", "Arolsen - new 2026/Pfullingen-list-1947-legible-copy-with-dates.jpg", 0,
  "documents", "The Pfullingen list, with the dates readable",
  "The same list of 10 March 1947 the family holds, but the Arolsen original. Six Defranceski with their arrival and departure dates: Felix from 5 July 1941; Ivan from 20 October 1941 to 5 September 1942; Anton, born 20.1.90, from 1 March to 13 June 1942 only; Zdravko from 17 June 1944; Ruža of Fužine from 29 July 1944. Felix, Zdravko and Ruža all leave on the same day — 3 March 1945.",
  "Arolsen Archives, DE ITS 2.1.3.1, ITS 154"),
 ("neuhausen-list", "Arolsen - new 2026/Neuhausen-list-1947-whole-family.jpg", 0,
  "documents", "The Neuhausen list, 25 March 1947",
  "Drawn up under General Koenig's Order No. 1792: every foreigner in the commune of Neuhausen an der Erms between September 1939 and April 1945. The first seven names are one family. Peter from 22 March 1941; Luise née Salzer, born in the village, «seit Geburt»; the daughters Ursula and Renate likewise; and Zdravko, Rose née Hreljec of Fužine/Belnica, and the infant Anton, all from 19 March 1945.",
  "Arolsen Archives, DE ITS 2.1.3.1, ITS 157"),
 # ---- other holdings -----------------------------------------------------
 ("omis-chart", "Research & Historical Documents/franceschi omis - family tree.jpg", 0,
  "documents", "The Omiš descent chart",
  "A hand-compiled chart of the Omiš and Zadar family, twenty generations deep, running from the fourteenth century to the twentieth. The later generations are omitted from this archive because the people in them may be living.",
  "Family collection (Omiš branch)"),
 ("bakar-1783", "Research & Historical Documents/ defranceschi 1783 bakar.png", 0,
  "documents", "Defranceschi at Bakar, 1783",
  "A register page kept with the family's research notes, placing the name at Bakar on the Kvarner coast in 1783.",
  "Family research collection"),
 ("moncalvo", "Research & Historical Documents/moncalvo.jpg", 0,
  "places", "Moncalvo di Pisino",
  "Gologorica under its Italian name — Moncalvo in the county of Pazin, where Carlo De Franceschi was born in 1809.",
  "Family research collection"),
 ("seget-view", "Research & Historical Documents/seget.jpeg", 0,
  "places", "Seget, near Umag",
  "The western-Istrian estate of the other branch, which reached Istria from Crete after the Candian War ended in 1669.",
  "Family research collection"),

 # ---- French zone: DP folder DP0758, Bad Arolsen, read Sept 2026 ---------
 ("fz-petar-fiche", "Arolsen - French Zone 2026/petar-fiche-photo.jpg", 0,
  "documents", "Petar's fiche individuelle, with his photograph",
  "The French occupation authorities' individual card. Nationality Yougoslav, born 15.06.13, profession Auto-mecancien, address Kelterstr. 30 Neuhausen, married. Card 30609; the number written across the head is 148.902 CB Bj. Five fingerprints in red ink, and a passport photograph: dark jacket, dark tie, hair combed back. Under Vaccins, in a clerk's hand: tetanus once, typhus twice.",
  "Arolsen Archives, DP folder DP0758 (03010101 05 070)"),
 ("fz-counselling", "Arolsen - French Zone 2026/counselling-front.jpg", 0,
  "documents", "The counselling card, front",
  "Headed COUNSELLING in a red box. DEFRANCESKI, Peter and Luise; IRO 148.902; category CB; born 15.6.13 Yougoslavie (Cirkvenica) and 5.10.19. Address, as at 1 April 1951: Kellterstrasse 30, Neuhaus Kr. Reutlingen. Under other members of the family, the wife and two children with their birth dates. Three lines under EXPOSE, dated 22.7.49, 28.4.51 and 25.5.51 — he wants to stay, he confirms it, and he is entered on the list of displaced persons living privately.",
  "Arolsen Archives, DP folder DP0758 (03010101 05 070)"),
 ("fz-counselling-back", "Arolsen - French Zone 2026/counselling-back.jpg", 0,
  "documents", "The counselling card, reverse",
  "Two columns, DATE and INTERVENTIONS, and one line written in them: 30.7.49 — «Proposons a Mr. Boesch de le mettre \u00abBj\u00bb». Eight days after Petar told the counsellor he had a house and two cars and meant to stay, the office proposed to reclassify him off IRO care.",
  "Arolsen Archives, DP folder DP0758 (03010101 05 070)"),
 ("fz-anton-australia", "Arolsen - French Zone 2026/anton-index-australia.jpg", 0,
  "documents", "The card that gives the day they left",
  "Reutlingen, 148.901. DEFRANCESKI, Anton 22.8.44 youg., a household of three, category CB. In ink across the middle: «Emigre Australie le 8.3.49», with 17.3.49 beneath it. At the foot, a red stamp: CM/1 destroyed — which is why no care-and-maintenance file survives for Zdravko's family, and why his brother has one.",
  "Arolsen Archives, DP folder DP0758 (03010101 05 070)"),
 ("fz-luise-apatride", "Arolsen - French Zone 2026/luise-index-apatride.jpg", 0,
  "documents", "Apatride",
  "Reutlingen, 148.902. «DEFRANCESKI, Luise 5.10.19 apatr.» — apatride, stateless; a household of four; category Bj. She was born German at Neuhausen in the Reutlingen district, and on marrying a Yugoslav in February 1942 took his nationality and lost her own. One abbreviated word is the whole of her legal position.",
  "Arolsen Archives, DP folder DP0758 (03010101 05 070)"),
 ("fz-petar-index", "Arolsen - French Zone 2026/petar-index-reutlingen.jpg", 0,
  "documents", "Petar's index card at Reutlingen",
  "Reutlingen, 148.902. DEFRANCESKI, Petar 15.6.13 youg., a household of four, category CB. Beneath, in four hands: «C.V. 15.12.45»; «73-(102) Re. 1, B. rev. 1./10.7.49»; «Tit 1165, 11.8.49, BJ»; «03.Tr.16, \u00abBJ\u00bb 23.8.49». The reclassification going through the books, one office at a time.",
  "Arolsen Archives, DP folder DP0758 (03010101 05 070)"),
 ("fz-petar-1951", "Arolsen - French Zone 2026/petar-fiche-1951.jpg", 0,
  "documents", "Stamped 16 October 1951",
  "The same printed form as his brother's child's card, filled for the man himself and stamped in red: 16 Okt 1951, IRO. The place of birth is written in by hand beside the typed date — Crikvenica. Marked BJ and CB across the head.",
  "Arolsen Archives, DP folder DP0758 (03010101 05 070)"),


 # ---- the family's own copy of the Reutlingen file, read Sept 2026 -------
 ("pf-zdravko-fiche", "Peter Family File 2026/zdravko-fiche.jpg", 0,
  "documents", "Zdravko's fiche individuelle, with his photograph",
  "Card 30560, IRO 148.901. DEFRANCESKI Zdravko, Yougoslav, born 01.04.21, Auto-mecanicien. Address Neuhausen, Friedrichstrasse 4. Five fingerprints in red and a small photograph: dark jacket, hair combed back, the same studio hand as his brother's. Arolsen's own copy of this household's file is stamped CM/1 destroyed; the family kept theirs.",
  "Family collection — the Reutlingen file"),
 ("pf-zdravko-card", "Peter Family File 2026/zdravko-dp-card.jpg", 0,
  "documents", "Zdravko's displaced-person identity card",
  "Commandement en chef francais en Allemagne, issued 27 November 1946. Height 175, brown eyes, chestnut hair; profession auto-mecanicien; married. And across the corner in red pencil, added later: 8/3/1949 Australie.",
  "Family collection — the Reutlingen file"),
 ("pf-ruza-anton", "Peter Family File 2026/ruza-with-anton.jpg", 0,
  "photographs", "Ruza, with Anton on her arm",
  "Card 30561. The photograph pasted to Ruza's fiche individuelle shows her holding the baby — the same child whose own card, a few numbers along, has the word enfant written across the fingerprint boxes in red crayon.",
  "Family collection — the Reutlingen file"),
 ("pf-ruza-card", "Peter Family File 2026/ruza-dp-card.jpg", 0,
  "documents", "Ruza's identity card, with the child",
  "Issued 27 November 1946 at Neuhausen, Friedrichstrasse 4. Born 13 February 1922 at Fusine, Yugoslavia; married. The photograph is of mother and child together. Annotated 8/3/1949 Austr.",
  "Family collection — the Reutlingen file"),
 ("pf-iro-letter", "Peter Family File 2026/iro-letter-1949.jpg", 0,
  "documents", "The letter that explains the code",
  "27 May 1949, from A. Poignant, Director of the IRO for the French zone, to the Chef de Service du Wurtemberg at Ebingen. Subject: «Cas de DEFRANCESKI (148.902)». Eligibility verified on 15.12.48 — and then the sentence the whole file turns on: «Le Chef de famille et les deux enfants sont classes B, l'epouse BJ.»",
  "Family collection — the Reutlingen file"),
 ("pf-health-brazil", "Peter Family File 2026/health-brazil.jpg", 0,
  "documents", "Screened for Brazil",
  "A small green slip signed by Dr S. Birietaite, Chef de Service de Sante: «M. Defranceski est passe au screening — Bresil», and beneath in blue, «Rien a signaler». He passed the medical for Brazil. He did not go.",
  "Family collection — the Reutlingen file"),
 ("pf-cert-zdravko", "Peter Family File 2026/cert-zdravko.jpg", 0,
  "documents", "Zdravko's Reutlingen certificate, 1950",
  "Stadt Reutlingen, stamped 28 February 1950: Defranceski Strawko, born 1.4.21 at Zvekvenica (Crikvenica), Croatian-Yugoslav, resident Pfullingen, employer Hermann Sauer, Reutlingen-Sud.",
  "Family collection — the Reutlingen file"),
 ("pf-cert-ruza", "Peter Family File 2026/cert-ruza.jpg", 0,
  "documents", "Ruza's Reutlingen certificate, 1950",
  "The same form, the same day: Defranceski Rose geb. Hreljac, born 13.2.22 at Fusine/Delnice, resident Pfullingen, employer Licht und Kraft, Reutlingen. Her birthplace is given here with its district — the fullest form the archive has.",
  "Family collection — the Reutlingen file"),

]

def run(cmd):
    r = subprocess.run(cmd, capture_output=True)
    if r.returncode:
        sys.stderr.write(" ".join(cmd[:3]) + " FAILED: " + r.stderr.decode()[:200] + "\n")
        return False
    return True

def main():
    os.makedirs(OUT, exist_ok=True)
    man, missing = [], []
    for pid, rel, rot, group, title, caption, holder in PLATES:
        src = os.path.join(DOCS, rel)
        if not os.path.exists(src):
            missing.append(rel); continue
        full = os.path.join(OUT, pid + ".webp")
        thumb = os.path.join(OUT, pid + "-t.webp")
        rotate = ["-rotate", str(rot)] if rot else []
        ok  = run(["magick", src, "-auto-orient"] + rotate +
                  ["-resize", "1800x1800>", "-quality", "82", full])
        ok &= run(["magick", src, "-auto-orient"] + rotate +
                  ["-resize", "700x700>", "-quality", "78", thumb])
        if not ok: continue
        w = h = 0
        try:
            out = subprocess.run(["magick", "identify", "-format", "%w %h", full],
                                 capture_output=True).stdout.decode().split()
            w, h = int(out[0]), int(out[1])
        except Exception:
            pass
        man.append({"id": pid, "group": group, "title": title, "caption": caption,
                    "holder": holder, "w": w, "h": h,
                    "src": f"/plates/{pid}.webp", "thumb": f"/plates/{pid}-t.webp"})
        print("ok", pid, f"{w}x{h}")
    json.dump(man, open(MAN, "w"), indent=1, ensure_ascii=False)
    print(f"\n{len(man)} plates -> {MAN}")
    if missing:
        print("MISSING:"); [print("  ", m) for m in missing]

if __name__ == "__main__":
    main()
